### ISSUE TITLE
ng-show toggling issue with Angular 1.3+

### ISSUE THREAD

**Issue by magizh** [m7r/grunt-ngdocs#132]
Experiencing the same issue as seen in the gulp-ngdocs plugin. 
https://github.com/nikhilmodak/gulp-ngdocs/issues/13

 ng-show, ng-if toggling doesn't work in the docs examples but works in a standalone app/page. 

No Errors seen in browser console.

**Comment by magizh** [comment]
Seems to have been fixed
 https://github.com/m7r/grunt-ngdocs/commit/9a9de1f9f6b05c36fd4203e6eadbdbd7453370a0

@m7r when is 0.2.7 coming out ? Docs with examples having ng-show toggle doesnt work with Angular 1.3.0.

**Comment by thomasponsvaltech** [comment]
+1 When the 0.2.7 coming out ? It's impossible to generate example that uses ng-show ... Can you make a release for this bugfix ?

**Comment by m7r** [comment]
likely tomorrow ;-)
