### ISSUE TITLE
How to turn off DEMO?

### ISSUE THREAD

**Issue by shekhardesigner** [m7r/grunt-ngdocs#134]
Hi @m7r 

Is there a way to turn off the DEMO section. I wish to keep just example section. My project is huge and copying all dev codes into documentation isn't suitable for my need hence wanted to turn-off demo.

Any advise?

**Comment by nhduc296** [comment]
+1

I want to add example code only. I have show case in another places.

OR: Are there any solution to config source root folder (of document app), So we easy to reuse dev source code

**Comment by m7r** [comment]
Just write your example like:

```
/**
 * @ngdoc directive
 * @name rfx.directive:rAutogrow
 * @element textarea
 * @function
 *
 * @description
 * Resize textarea automatically to the size of its text content.
 *
 * @example
 *  ```html
 *  <textarea ng-model="text" r-autogrow class="input-block-level"></textarea>
 *  ```
 * More info
 */
```

**Comment by shekhardesigner** [comment]
Perfect! Thanx

**Comment by nhduc296** [comment]
Hi @m7r,

How about the example javascript code, how do I separate example code with tabed like normal example but I don't want it execute

**Comment by m7r** [comment]
That's at the moment not directly possible.
