### ISSUE TITLE
Handle method names that match Bootstrap classes

### ISSUE THREAD

**Issue by peterhodges** [m7r/grunt-ngdocs#136]
The method's @name is used as the className for the wrapper element around the method's section in the docs.

When this class name matches one of the Bootstrap classes, mayhem occurs.

![ngdocs_example](https://cloud.githubusercontent.com/assets/5931545/6082983/56061e7e-ae1d-11e4-841d-06e10c79570d.png)

![ngdocs_element_inspector](https://cloud.githubusercontent.com/assets/5931545/6082986/5a49547e-ae1d-11e4-8cda-82dbf437be7e.png)

**Comment by m7r** [comment]
fixed in 0.2.7 release likely tomorrow
