### ISSUE TITLE
Directive bi-directional binding parameter type (string=) error.

### ISSUE THREAD

**Issue by paulcoyle** [m7r/grunt-ngdocs#138]
When trying to use `@param {string=}` I get the following error:

    Warning: Not a valid 'param' format: {string=}

Is this supported?

**Comment by m7r** [comment]
The format is `@param {string=} name description`

name and description are required.

**Comment by paulcoyle** [comment]
I am using that form, though. The snippet above was for brevity.

**Comment by paulcoyle** [comment]
My mistake, I was including an incomplete file that was missing the description.  Sorry!
