### ISSUE TITLE
git tags

### ISSUE THREAD

**Issue by gnuheidix** [m7r/grunt-ngdocs#140]
Hi,
could you please create a new git tag after you've released a new version like 0.2.7. This would make source code browsing and comparison a lot easier. 
Thanks a lot and keep up the good work :-)

Best regards
Thomas
![ngdocs](https://cloud.githubusercontent.com/assets/234757/6411187/6f0441b2-be76-11e4-83ae-7a335df8e83e.png)

**Comment by m7r** [comment]
pushed tags ;-)

**Comment by gnuheidix** [comment]
awesome response time, thanks :)
