### ISSUE TITLE
Example app not working with AngularJS 1.2 version

### ISSUE THREAD

**Issue by jintoppy** [m7r/grunt-ngdocs#141]
In my app, I am using AngularJS 1.2.27. 

I tried to create a demo app in the documentation. I tried with giving module name, without module name, but everytime getting error that, "App Already Bootstrapped with this Element". It started working only when I was using only 'angular.js' in scripts which is loading v1.1.5. 

It seems like this will work in only in old version. Any idea why this is happening? 

Thanks in advance

**Comment by m7r** [comment]
Which version of grunt-ngdocs do you use? 0.2+ is required for AngularJS 1.2+

**Comment by jintoppy** [comment]
Got it. My bad. I updated the version and it works fine. Thanks
