### ISSUE TITLE
Calculation of baseUrl

### ISSUE THREAD

**Issue by oravecz** [m7r/grunt-ngdocs#142]
I'm not sure I understand the logic behind how baseUrl is calculated. Currently, if I place my API documentation at the url http://example.org/sites/myapp/api/, the baseUrl resolves to http://example.org/sites/myapp. Unfortunately, all of the css and js files loaded exist alongside the index.html in the http://example.org/sites/myapp/api/ directory.

Why not: 
1. use relative pathing for the resources? 
2. calculate the baseUrl by simply using the context path of the index.html page?
3. allow passing of baseUrl as an option? (Not ideal because of differences of this value based on environment builds.)

**Comment by m7r** [comment]
The problem here is the name of the dir 'api' as this is the name of the default section.

A url would read like http://example.org/sites/myapp/api/api/app.common.directive:myDirective in html5 mode.

There are two possibilities:

  - change the name of the section
  - change the name of the dir
