### ISSUE TITLE
Sources not loaded in Firefox

### ISSUE THREAD

**Issue by Srogozins** [m7r/grunt-ngdocs#149]
Opening the generated index.html in FF 37.0.1 leads to following picture 
![screenshot from 2015-04-25 15 51 08](https://cloud.githubusercontent.com/assets/6780626/7332939/fee4c5c2-eb62-11e4-827e-2e7ef619c093.png)
Inspecting sources showed that the browser hadn't loaded anything except index.html.

I'm using Angular 1.3+, but the problem persists both when using the original angular files and including the ones in my bower_components to grunt-scripts. In Chrome 42 the problem never occurs.

**Comment by phreezer** [comment]
I was seeing this issue as well, if you serve the files from a web server it will work. It is probably a local file path issue.

**Comment by m7r** [comment]
please try 0.2.8
