### ISSUE TITLE
Don't know how to format @ngdoc: provider Use

### ISSUE THREAD

**Issue by chfw** [m7r/grunt-ngdocs#151]
Hi

I am just wondering why ngdocs does not understand 'provider' as angular.js had 'provider' for long and their documentation had ['provider'](https://github.com/angular/angular.js/blob/9b35dfb658411ff12ded73be44e52072e43e0c1c/src/ngCookies/cookies.js) too. So is true that ngdocs does not know 'provider'?

Br

**Comment by kevinfarrugia** [comment]
Hi chfw,

I have noticed this issue just recently and will create a pull request. It recognizes provider but has an issue when generating the provider url in the template.

**Comment by m7r** [comment]
try 0.2.8

**Comment by kavi87** [comment]
Hi,
I've tried with 0.2.8 but the error still appear: "Warning: Don't know how to format @ngdoc: provider Use --force to continue."

When using 

/**
     * @ngdoc provider
     * @name myModule.provider:MyServiceProvider
     */

**Comment by m7r** [comment]
use:
```js
/**
 * @ngdoc service
 * @name myModule.myServiceProvider
 */
```

**Comment by chfw** [comment]
verified with 0.2.9
