### ISSUE TITLE
Source URL

### ISSUE THREAD

**Issue by eddiemonge** [m7r/grunt-ngdocs#164]
Given this url https://github.com/angular-ui/ui-router/blob/master/package.json#L29 the `View Source` and `Improve this Doc` are incorrect. They are trying to point to 

> github.com/angular-ui/ui-router**.git**/blob/a980f89/src/urlMatcherFactory.js#L68

instead of 

> github.com/angular-ui/ui-router/blob/a980f89/src/urlMatcherFactory.js#L68

The incorrect part is the `.git` extension is not being stripped out.

**Comment by m7r** [comment]
should be fixed in 0.2.9

**Comment by eddiemonge** [comment]
You should look at https://github.com/zeke/github-url-to-object for that functionality
