### ISSUE TITLE
Partials aren't generated

### ISSUE THREAD

**Issue by GBora** [m7r/grunt-ngdocs#184]
Hello, this is my config:

```
ngdocs: {
           options: {
               dest: 'docs',
               html5Mode: false,
               scripts: [
                   'bower_components/angular/angular.js',
                   'bower_components/angular-animate/angular-animate.js'
               ]
           },
           api: {
               src: [angularFiles],
               title: 'Docs'
           }
        },

```

And running the task the output seems legit:

```
$ grunt ngdocs
Running "ngdocs:api" (ngdocs) task
Generating Documentation...
DONE. Generated 2 pages in 1154ms.
```

Since I've started off by marking only two files with comments, going to the site everithing looks fine at first, see atached image
![docs](https://cloud.githubusercontent.com/assets/3342157/11301080/ed455366-8f9c-11e5-8128-8b2aa2567f50.png)

But when I click on pattern validator for example it's partial (where I assume it's description should be) doesn't load, and I can't find the two pages it said it generated in the partials folder.

And example of me tagging my directives as maybe I'm doing it wrong:

```
angular.module('passwordModule')
    /**
     * @ngdoc directive
     * @name passwordStrength
     * @id directive
     * @description Shows a pop-up with details about the password strength
     */
    .directive('passwordStrength', [
```

**Comment by blackmjck** [comment]
@GBora It looks like your tagging is off in that example. Try something like this:
```javascript
angular.module( 'passwordModule' )
    /**
     * @ngdoc directive
     * @name passwordModule.directive:passwordStrength
     * @description Shows a pop-up with details about the password strength
     */
    .directive( 'passwordStrength', [...```

**Comment by GBora** [comment]
@blackmjck Thanks I'll try that.
